device_name: Atlas
device_type: speaker

zeroconf_enabled: false
credentials:
  type: interactive

server:
  enabled: true
  address: localhost
  port: 3678

audio_backend: pipe
audio_output_pipe: /tmp/atlas-music.fifo
audio_output_pipe_format: s16le
audio_output_pipe_wait_for_reader: true

bitrate: 320
crossfade_duration: 0
normalisation_disabled: true

volume_steps: 100
initial_volume: 100
external_volume: false

cache:
  enabled: true
