import os
from pathlib import Path
from zoneinfo import ZoneInfo

ROOT = Path(__file__).parent
DATABASE_PATH = Path(
    os.environ.get("ATLAS_DATABASE_PATH", ROOT / "data" / "atlas_v2.db")
)
TOOLS_PATH = ROOT / "tools.json"
HOST = "127.0.0.1"
PORT = 8090
TIMEZONE = ZoneInfo("America/Los_Angeles")
SCHEDULER_INTERVAL_SECONDS = 0.5

SPEAKER_MODEL_NAME = "speechbrain/spkrec-ecapa-voxceleb"
SPEAKER_MODEL_DIR = ROOT / "data" / "speaker_model"
SPEAKER_UNKNOWN_STREAK_FOR_ENROLLMENT = 5
SPEAKER_IDENTIFY_MIN_SECONDS = 2.0
SPEAKER_ENROLLMENT_MIN_SECONDS = 5.0
SPEAKER_REINFORCE_MIN_SECONDS = 5.0
SPEAKER_MAX_SAMPLES = 10

# similarity thresholds
SPEAKER_REVIEW_THRESHOLD = 0.40
SPEAKER_KNOWN_THRESHOLD = 0.60
SPEAKER_REINFORCE_THRESHOLD = 0.70
SPEAKER_REDUNDANCY_THRESHOLD = 0.95
