import os
from pathlib import Path
from zoneinfo import ZoneInfo

ROOT = Path(__file__).parent
DATABASE_PATH = Path(
    os.environ.get("ATLAS_DATABASE_PATH", ROOT / "data" / "atlas_v2.db")
)
TOOLS_PATH = ROOT / "tools.json"
HOST = "127.0.0.1"
PORT = 8090
TIMEZONE = ZoneInfo("America/Los_Angeles")
SCHEDULER_INTERVAL_SECONDS = 0.5

SPEAKER_MODEL_NAME = "speechbrain/spkrec-ecapa-voxceleb"
SPEAKER_MODEL_DIR = ROOT / "data" / "speaker_model"
SPEAKER_IDENTIFY_MIN_SECONDS = 2.0
SPEAKER_ENROLLMENT_MIN_SECONDS = 4.0
SPEAKER_REINFORCE_MIN_SECONDS = 4.0
SPEAKER_MAX_SAMPLES = 10

# similarity thresholds
SPEAKER_REVIEW_THRESHOLD = 0.35
SPEAKER_KNOWN_THRESHOLD = 0.50
SPEAKER_REINFORCE_THRESHOLD = 0.60
SPEAKER_REDUNDANCY_THRESHOLD = 0.90

SPEAKER_ANONYMOUS_GC_INTERVAL_SECONDS = 24 * 60 * 60
SPEAKER_ANONYMOUS_ASK_CADENCE = 3
